GET http://localhost:3001/api/patrient/list
#####
POST http://localhost:3001/api/patrient
#####
PUT http://localhost:3001/api/patrient/62530d09c412056d5cba973e
#####
DELETE http://localhost:3001/api/patrient/625311fd5d08b9769c485fca